export const NAVY_BLUE = '#083A9B';
export const LIGHT_YELLOW = '#FFF6C7';
export const BANANA_YELLOW = '#FFE145';
export const WHITE = '#FFFFFF';
export const GRAY = '#F0EEEE';
export const WHITE_TRANSPARENT = 'rgba(255, 255, 255, 0.6)';
export const LIGHT_GRAY_DISABLED = '#C4C4C4';
export const DARK_GRAY = 'rgb(60, 60, 60)';
export const DARK_GRAY_TRANSPARENT = 'rgba(60, 60, 60, .5)';
